
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
    # Check for updates to GitHub Actions every weekday
      interval: "daily"
